### ISSUE TITLE
Package mirrors

### ISSUE THREAD

**Issue by mostvotedplaya** [jelaas/bifrost-build-x86_64#2]
Hi,

I was wondering if you could update the mirrors used to download packages as it seems ftp.sunet.se is
no longer working.

A quick script to fix this would be:

```
#!/usr/bin/env bash

for path in all/*
do
     sed -i "s/ftp.sunet.se/sunsite.icm.edu.pl/g" "$path/Fetch-source.sh"
done
```

Thanks

**Comment by jelaas** [comment]
On Wed, 9 Mar 2016, Lee Howarth wrote:

> 
> Hi,
> 
> I was wondering if you could update the mirrors used to download packages as it seems ftp.sunet.se is
> no longer working.

Thanks!

Taken!

Cheers,
Jens
